//This code was generated by T4 Template.

using System.Globalization;

namespace System
{
    public static partial class Maybe
    {
        public static Option<Byte> ParseByte(string s)
        {
            Byte result;
            if (Byte.TryParse(s, out result))
            {
                return Option.Some(result);
            }

            return Option.None<Byte>();
        }

        public static Option<Byte> ParseByte(string s,
            NumberStyles style,
            IFormatProvider provider)
        {
            Byte result;
            if (Byte.TryParse(s, style, provider, out result))
            {
                return Option.Some(result);
            }

            return Option.None<Byte>();
        }
    }
}
