//This code was generated by T4 Template.

using System.Globalization;

namespace System
{
    public static partial class Maybe
    {
        public static Option<Double> ParseDouble(string s)
        {
            Double result;
            if (Double.TryParse(s, out result))
            {
                return Option.Some(result);
            }

            return Option.None<Double>();
        }

        public static Option<Double> ParseDouble(string s,
            NumberStyles style,
            IFormatProvider provider)
        {
            Double result;
            if (Double.TryParse(s, style, provider, out result))
            {
                return Option.Some(result);
            }

            return Option.None<Double>();
        }
    }
}
