//This code was generated by T4 Template.

using System.Globalization;

namespace System
{
    public static partial class Maybe
    {
        public static Option<Int64> ParseInt64(string s)
        {
            Int64 result;
            if (Int64.TryParse(s, out result))
            {
                return Option.Some(result);
            }

            return Option.None<Int64>();
        }

        public static Option<Int64> ParseInt64(string s,
            NumberStyles style,
            IFormatProvider provider)
        {
            Int64 result;
            if (Int64.TryParse(s, style, provider, out result))
            {
                return Option.Some(result);
            }

            return Option.None<Int64>();
        }
    }
}
