//This code was generated by T4 Template.

using System.Globalization;

namespace System
{
    public static partial class Maybe
    {
        public static Option<Decimal> ParseDecimal(string s)
        {
            Decimal result;
            if (Decimal.TryParse(s, out result))
            {
                return Option.Some(result);
            }

            return Option.None<Decimal>();
        }

        public static Option<Decimal> ParseDecimal(string s,
            NumberStyles style,
            IFormatProvider provider)
        {
            Decimal result;
            if (Decimal.TryParse(s, style, provider, out result))
            {
                return Option.Some(result);
            }

            return Option.None<Decimal>();
        }
    }
}
