//This code was generated by T4 Template.

using System.Globalization;

namespace System
{
    public static partial class Maybe
    {
        public static Option<Int16> ParseInt16(string s)
        {
            Int16 result;
            if (Int16.TryParse(s, out result))
            {
                return Option.Some(result);
            }

            return Option.None<Int16>();
        }

        public static Option<Int16> ParseInt16(string s,
            NumberStyles style,
            IFormatProvider provider)
        {
            Int16 result;
            if (Int16.TryParse(s, style, provider, out result))
            {
                return Option.Some(result);
            }

            return Option.None<Int16>();
        }
    }
}
