//This code was generated by T4 Template.

using System.Globalization;

namespace System
{
    public static partial class Maybe
    {
        public static Option<Int32> ParseInt32(string s)
        {
            Int32 result;
            if (Int32.TryParse(s, out result))
            {
                return Option.Some(result);
            }

            return Option.None<Int32>();
        }

        public static Option<Int32> ParseInt32(string s,
            NumberStyles style,
            IFormatProvider provider)
        {
            Int32 result;
            if (Int32.TryParse(s, style, provider, out result))
            {
                return Option.Some(result);
            }

            return Option.None<Int32>();
        }
    }
}
