//This code was generated by T4 Template.

using System.Globalization;

namespace System
{
    public static partial class Maybe
    {
        public static Option<Single> ParseSingle(string s)
        {
            Single result;
            if (Single.TryParse(s, out result))
            {
                return Option.Some(result);
            }

            return Option.None<Single>();
        }

        public static Option<Single> ParseSingle(string s,
            NumberStyles style,
            IFormatProvider provider)
        {
            Single result;
            if (Single.TryParse(s, style, provider, out result))
            {
                return Option.Some(result);
            }

            return Option.None<Single>();
        }
    }
}
